language = "C"

include_guard = "CHEATSCAN_TYPES_H"

[export]
exclude = ["cheatscan_*"]
include = [
  "Alignment",
  "ComparisonType",
  "Endianness",
  "ScanError",
  "ValueType",
  "Configuration"
]